version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5963 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "5963:5963"
    depends_on:
      - db
